[env:cyd]
platform  = espressif32@6.6.0
board     = esp32dev
framework = arduino

monitor_speed   = 115200
upload_speed    = 921600
monitor_filters = esp32_exception_decoder

board_build.f_cpu       = 240000000L
board_build.f_flash     = 80000000L
board_build.flash_mode  = qio
board_build.partitions  = default.csv

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DLV_CONF_INCLUDE_SIMPLE
    -DLGFX_USE_V1
    -DCONFIG_BT_NIMBLE_ENABLED=1
    -DCONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
    -DCONFIG_BT_NIMBLE_MAX_BONDS=1
    -DCONFIG_BT_NIMBLE_MAX_CCCDS=3
    -DCONFIG_BT_NIMBLE_ATT_PREFERRED_MTU=517
    -I "${PROJECT_INCLUDE_DIR}"

lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    lvgl/lvgl @ 8.3.11
    h2zero/NimBLE-Arduino @ 1.4.3
    bblanchon/ArduinoJson @ ^6.21.5